config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'groups#index'

  resources :groups do
    resources :messages
  end
  resources :users, only: [:edit, :update] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true

  def members
    members=""
    self.users.each do |user|
      members += "#{user.name}　"
    end
    members
  end

  def last_message
    self.messages.presence ? messages.last.body : 'メッセージはありません'
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body_or_image, presence: true

  mount_uploader :image, ImageUploader

  def body_or_image
    body.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group.id), notice: '新規グループを作成しました'
    else
      render 'new'
    end

  end

  def edit
    @group = Group.find(params[:id])
    @members = @group.users.where.not(id: current_user.id)
    # @members.delete(id: current_user.id)
    # @members.map{|member|member.delete if member.id == current_user.id }
  end

  def update
    # binding.pry
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path
    else
    end
  end

  def destroy
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages

    #サイドバーの表示用
    @groups = Group.all

    @message = Message.new
  end

  def new
  end

  def create
    @message = Message.new(message_params)

    #render用の変数
    @group = Group.find(params[:group_id])
    @groups = Group.all
    @messages = @group.messages

    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(params[:group_id]) }
        format.json
      end
    else
      render 'index'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  def search
    @users = User.where.not(id: current_user.id).where('name like ?', "#{params[:search_key]}%") #.where.not('user_id #{current_user.id}')
    respond_to do |format|
      format.json
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/helpers/messages_helper.rb
module MessagesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group_form.html.haml
.form-body
  .chat-group-form
    =form_for(@group, id: 'edit_chat_group', class: 'edit_chat_group') do |f|
      - if @group.errors.any?
        .chat-group-form__errors
          %h2
            ="#{@group.errors.count}件のエラーが発生しました"
            %ul
              - @group.errors.full_messages.each do |error|
                %li
                  =error
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_name"} グループ名
        .chat-group-form__field--right
          = f.text_field :name, id: 'chat_group_name', class: 'chat-group-form__input'

      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{for: "chat_group"}追加
        #add-current-user.chat-group-form__field--right
          .chat-group-form__search
            = f.text_field :id, value: '', id: 'chat_group_user', class: 'chat-group-form__input', placeholder: '追加したいユーザー名を入力してください'

          .current-users.clearfix
            .current-users-name
              =current_user.name
              = f.hidden_field :user_ids, value: current_user.id, name: "group[user_ids][]", id: "group_user_ids"
          -if members
            -members.each do |member|
              .current-users.clearfix
                .current-users-name
                  =member.name
                .remove-user-btn
                  %i.fa.fa-times
                = f.hidden_field :user_ids, value: member.id, name: "group[user_ids][]", id: "group_user_ids"

      .chat-group-form__field.clearfix
        .chat-group-form__field--left
        .chat-group-form__field--right
          #group-members

      .chat-group-form__field.clearfix
        .chat-group-form__field--left
        .chat-group-form__field--right
          #user-search-result
      = f.submit 'submit', class: 'chat-group-form__action-btn'

app/views/groups/create.html.haml
%h1 Groups#create
%p Find me in app/views/groups/create.html.haml

app/views/groups/destroy.html.haml
%h1 Groups#destroy
%p Find me in app/views/groups/destroy.html.haml

app/views/groups/edit.html.haml
= render 'group_form', members: @members

app/views/groups/index.html.haml
.side-bar
  =render partial: '/shared/side-bar', locals: { groups: @groups }

.main
  .main__top
  .main__contents
  .post

app/views/groups/new.html.haml
= render 'group_form', members: nil

app/views/groups/update.html.haml
%h1 Groups#update
%p Find me in app/views/groups/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KissaChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    -if flash[:notice]
      #notice
        =flash[:notice]
    -if  @message && @message.errors && @message.errors.any?
      #notice
        %ul
          -@message.errors.full_messages.each do |error|
            %li
              =error
    = yield

app/views/messages/_message.html.haml
.main__contents__message{"data-message-id": message.id}
  .main__contents__message_body
    =message.body
  .main__contents__message_image
    =image_tag message.image
  .main__contents__message_name
    =message.user.name

app/views/messages/create.html.haml
%h1 Messages#create
%p Find me in app/views/messages/create.html.haml

app/views/messages/destroy.html.haml
%h1 Messages#destroy
%p Find me in app/views/messages/destroy.html.haml

app/views/messages/edit.html.haml
%h1 Messages#edit
%p Find me in app/views/messages/edit.html.haml

app/views/messages/index.html.haml
.side-bar
  =render partial: '/shared/side-bar', locals: { groups: @groups }

.main
  .main__top
    .main__top__group
      =@group.name
    .main__top__group_members
      =@group.members
    .main__top__edit
      .main__top__edit_box
        =link_to 'EDIT', edit_group_path(@group.id)
  .main__contents
    =render partial: 'message', collection: @messages
  .main__post
    .main__post__forms
      = form_for [@group, @message] do |f|
        = f.text_field :body, class: 'input-form'
        = f.label :image, class: 'file-form-icon' do
          %i.fa.fa-picture-o
        = f.file_field :image, class: 'file-form'
        = f.submit 'POST', class: 'submit'

app/views/messages/new.html.haml
%h1 Messages#new
%p Find me in app/views/messages/new.html.haml

app/views/messages/update.html.haml
%h1 Messages#update
%p Find me in app/views/messages/update.html.haml

app/views/shared/_group.html.haml
.side-bar__lists__item
  .side-bar__lists__item_group-label
    =link_to group.name, group_messages_path(group.id)
  .side-bar__lists__item_message-label
    / =group.messages.last.body
    =group.last_message

app/views/shared/_side-bar.html.haml
.side-bar__top
  .side-bar__top__labels
    .side-bar__top__labels_current-user
      =current_user.name
    .side-bar__top__labels_icons
      .side-bar__top__labels_icons_edit
        = link_to edit_user_path(current_user.id) do
          %i.fa.fa-pencil
      .side-bar__top__labels_icons_new
        = link_to new_group_path do
          %i.fa.fa-plus

.side-bar__lists
  = render partial: '/shared/group', collection: groups

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Edit Account", class: 'btn'

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml